# Setup
title:               Yousuf's Blog
tagline:             'Sharing what I know.'
description:         'I'm <a href="https://www.linkedin.com/in/yousuf-al-hinai" target="_blank">Yousuf Al Hinai</a> , a lecturer at the IT Dept., <a href="http://twitter.com/UTASIbri" target="_blank">UTAS, Ibri</a>. I'm passionate about software & web development, databases, and AI.'
url:                 https://yousufsaif.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yousuf Saif Al Hinai
  url:               https://twitter.com/yousufalhinai
  email:             yousuf_saif@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-YY
